// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/7/2025, 8:29:22 π.μ.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/projects/nuxt-starter-wgfndmem/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-wgfndmem/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-wgfndmem/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-wgfndmem/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-wgfndmem/plugins/**/*.{js,ts,mjs}","/home/projects/nuxt-starter-wgfndmem/composables/**/*.{js,ts,mjs}","/home/projects/nuxt-starter-wgfndmem/utils/**/*.{js,ts,mjs}","/home/projects/nuxt-starter-wgfndmem/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-wgfndmem/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-wgfndmem/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-wgfndmem/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;