// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25/7/2025, 12:58:24 μ.μ.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/alik3dav/Sprigggy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/Sprigggy/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/Sprigggy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/Sprigggy/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/Sprigggy/plugins/**/*.{js,ts,mjs}","/home/alik3dav/Sprigggy/composables/**/*.{js,ts,mjs}","/home/alik3dav/Sprigggy/utils/**/*.{js,ts,mjs}","/home/alik3dav/Sprigggy/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/Sprigggy/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/Sprigggy/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/Sprigggy/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;