// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/7/2025, 11:29:45 π.μ.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/alik3dav/ZippyKit/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/ZippyKit/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/ZippyKit/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/ZippyKit/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/ZippyKit/plugins/**/*.{js,ts,mjs}","/home/alik3dav/ZippyKit/composables/**/*.{js,ts,mjs}","/home/alik3dav/ZippyKit/utils/**/*.{js,ts,mjs}","/home/alik3dav/ZippyKit/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/ZippyKit/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/ZippyKit/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/alik3dav/ZippyKit/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;